### PR TITLE
Upgrade to React 18

### LINKED ISSUE #216: Update react to v18
This should not have any major issues, just some find and replaces.
Will also need QA to properly go through PR and look for regressions before merging.

### PR DESCRIPTION
**Pull request by dcrescimbeni**
# Description

1. Upgraded to React v18.
2. Upgraded to react-router v6 because of compatibility issues.
3. Upgraded typings and minor versions of other libraries. 
4. Updated tests.

Closes #216 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Upgrade

# How Has This Been Tested?

Manual testing. All existing tests passed.

# Checklist:

- [ ] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rossneilson** [comment]
@Filipv95 An important one to run through QA for regressions

**Comment by dcrescimbeni** [comment]
A major change was the upgrade of react-router, from v5 to v6. I had to change some navigation logic, but nothing major.

I manually tested the navigation, and seems like everything is working OK, but it could be beneficial to test it again.

A note for the future, we can implement nested routes using the `<Outlet>` component.

**Comment by Filipv95** [comment]
@rossneilson @dcrescimbeni I've done regression test on this PR, I've noticed couple of things that do not work:

1. Unable to execute Transfer Proposal (previously I've successfully executed 'Set permission' proposal for SWPR token)

https://user-images.githubusercontent.com/37701286/185745672-8cb4bfc2-8369-4ac0-a58c-4d6bc0387a02.mp4

2. Number of SWPR tokens is not the same for 'Transfer & Mint' and 'Set permission' actions (fixed in #227, check screen record)

https://user-images.githubusercontent.com/37701286/185745659-69c29676-9fcd-4601-8571-59d993f1ef0b.mp4

3. 'Unknown token' appears for vesting action - could this be because the fix (#230) is not merged to this PR?

**Comment by dcrescimbeni** [comment]
Seems that the errors stem from not merging the last PRs, thankfully not because of the upgrade.

I'll merge them and let you know

**Comment by dcrescimbeni** [comment]
Everything should be working now

**Review by rossneilson — APPROVED** [review]

**Comment by Filipv95** [comment]
@rossneilson @dcrescimbeni I checked all bugs from last comment and now all looks ok.

1. Able to execute Transfer Proposal (previously I've successfully executed 'Set permission' proposal for SWPR token)
2. Number of SWPR tokens is the same for 'Transfer & Mint' and 'Set permission' actions
3.  For Vesting action the unknown token no longer appears

**Pull request merged**
