### PR TITLE
Fix staking modal title

### LINKED ISSUE #194: In Title of 'Stake SWAP' window word 'token' is duplicated
**Description**
At Title of 'Stake SWAP' window I can see 'Stake SWAP Token tokens'. Word 'token' is duplicated 

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on 'Join' button

**Expected behavior**
At Title of 'Stake SWAP' window expect to see 'Stake SWAP Tokens'

**Screenshots**
Screenshot 2022-08-08 at 18 11 04

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

### PR DESCRIPTION
**Pull request by mprasanjith**
# Description

Fixes title in staking modal. Also cleans up the staking modal components.

Closes #194.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by Filipv95** [comment]
Hey @mprasanjith, check this PR, looks good to me!

**Review by Kenny-Gin1 — DISMISSED** [review]
LGTM! Much cleaner and good proper use of `children` instead!

**Comment by Kenny-Gin1** [comment]
You have some failing integration tests, not sure if it is related to your fix or not.

**Comment by dcrescimbeni** [comment]
> You have some failing integration tests, not sure if it is related to your fix or not.

It's a bug related to the approve/lock modal. The functionality is correct, but I think there's a difference in the UI.

@MiltonTulli referenced this on a call some days ago.

**Review by dcrescimbeni — APPROVED** [review]

**Pull request merged**
