### PR TITLE
fix: made it possible to create DXD vesting contract

### PR DESCRIPTION
**Pull request by Kenny-Gin1**
# Description

Bug was causing the UI to crash when trying to create a DXD vesting contract.

Closes # (issue)
Issue: https://github.com/DXgovernance/DAVI/issues/143

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manually. 
# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by dcrescimbeni** [comment]
When creating a vesting contract, it adds a second call to the "Against" option.

Is this intended?

Video:
https://www.loom.com/share/70b31e94e69b4ba9bb3197300067303b

**Review by MiltonTulli — APPROVED** [review]
Looks good to me!

**Comment by rossneilson** [comment]
> When creating a vesting contract, it adds a second call to the "Against" option.
> 
> Is this intended?
> 
> Video: https://www.loom.com/share/70b31e94e69b4ba9bb3197300067303b

This seems like we are adding the approval required for a vesting contract call to the option one index along. Lets check this Kenny and ensure the approval is in the same option as the contract call itself

**Review by rossneilson — APPROVED** [review]

**Comment by Kenny-Gin1** [comment]
> > > When creating a vesting contract, it adds a second call to the "Against" option.
> > > Is this intended?
> > > Video: https://www.loom.com/share/70b31e94e69b4ba9bb3197300067303b
> > 
> > 
> > This seems like we are adding the approval required for a vesting contract call to the option one index along. Lets check this Kenny and ensure the approval is in the same option as the contract call itself
> 
> Good catch! My changes just made sure it didn't crash so it must have been wrong in the implementation since before. But I'll make a change in this PR!

Decided on a call to make a new issue of the above-mentioned problem: https://github.com/DXgovernance/DAVI/issues/173

**Pull request merged**
