### PR TITLE
First Orbis implementation

### PR DESCRIPTION
**Pull request by Kenny-Gin1**
# Description

This is the first implementation of Orbis to DAVI. It required a few updates to our dependencies and webpack configurations and thus will include breaking changes. In the first implementation, we will have a button that redirects us to `:guildAddress/discussion` and from there we will connect to Orbis and be able to create our first post.

- Adds the Orbis implementation (Ceramic Client) to DAVI.
- Adds a **Create Discussion** button beside the  **Create Proposal** button. 
- `connect`,** `isConnected`, `createPost`-methods to interact with Orbis
- Updating `react-scripts` from 4.0.3 to 5.0.1
- Configuration updates to Webpack to work with Ceramic
- Test added for `postTemplate`

TODO: 
- Add more functionalities to the `createPost` method to allow for mentions, replies, master references, and so on.
- Add integration test for our `CreateDiscussion`-page
- Refactor the state management in the CreateDiscussion page to maybe use `useReducer` or.`useContext`

Screenshot 2022-08-10 at 14 53 47

Screenshot 2022-08-10 at 14 55 12

Screenshot 2022-08-10 at 14 55 43

Closes # [(issue)](https://github.com/DXgovernance/DAVI/issues/175)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rossneilson** [comment]
Can we set `master` to be guildId, otherwise no way of retrieving posts

**Comment by Kenny-Gin1** [comment]
> Can we set `master` to be guildId, otherwise no way of retrieving posts

I think you mean `context`? `master` will be used by a parent comment. It is done regardless!

**Comment by rossneilson** [comment]
> > Can we set `master` to be guildId, otherwise no way of retrieving posts
> 
> I think you mean `context`? `master` will be used by a parent comment. It is done regardless!

Ah yes, thank you! context is correct

**Review by rossneilson — APPROVED** [review]

**Comment by Filipv95** [comment]
@rossneilson @Kenny-Gin1  
 I've checked the PR, if I understood correctly, after I click on 'Create Discussion' button I should be redirected to Guilds page and that's it? I.e. no actual discussion box should appear on Guilds page?
 
 Is there anything else I should check? 
 
 If not, this all seems good.

**Comment by rossneilson** [comment]
> @rossneilson @Kenny-Gin1 I've checked the PR, if I understood correctly, after I click on 'Create Discussion' button I should be redirected to Guilds page and that's it? I.e. no actual discussion box should appear on Guilds page?
> 
> Is there anything else I should check?
> 
> If not, this all seems good.

That's correct, we will fill out a full path for discussions later. 
We are also updating a lot of dependencies so might also be worth running through other happy path tests for this PR also?

**Comment by Kenny-Gin1** [comment]
> @rossneilson @Kenny-Gin1 I've checked the PR, if I understood correctly, after I click on 'Create Discussion' button I should be redirected to Guilds page and that's it? I.e. no actual discussion box should appear on Guilds page?
> 
> Is there anything else I should check?
> 
> If not, this all seems good.

Yes, as @rossneilson mentioned. But might be worth doing a regression test on this one and see if anything is broken or in accordance with the current issues :).

**Comment by Filipv95** [comment]
@rossneilson @Kenny-Gin1  Awesome, tnx! 

Ofc, I'm doing regression testing basically after every push ^^

**Comment by rossneilson** [comment]
How have we gone this long without QA
If you give us an approval we'll go ahead and merge :)

**Comment by Filipv95** [comment]
@rossneilson Ack, I'll let you know when I finish with regression testing.

**Comment by Kenny-Gin1** [comment]
@Filipv95 Whenever we get DAVI to production, we will probably be working more with version control so that you (the QA) can test the version properly. Cannot be super fun working with an ever-changing code base with things breaking. But thanks for all the issues and bugs you've reported so far. Super valuable and appreciated :D

**Comment by Filipv95** [comment]
@rossneilson I've finished with regression testing - **I found no regression**, which is good and we have same behavior overall,  except 'known issues' ofc.

I found couple of bugs which I'm very certain existed before this push. I'll log those.

**Comment by Filipv95** [comment]
> @Filipv95 Whenever we get DAVI to production, we will probably be working more with version control so that you (the QA) can test the version properly. Cannot be super fun working with an ever-changing code base with things breaking. But thanks for all the issues and bugs you've reported so far. Super valuable and appreciated :D

I just love what I do so I'm looking forward to it! :D 
Ofc, thank you also for your support and helping and everything, appreciate it! ^^

**Comment by Kenny-Gin1** [comment]
> @rossneilson I've finished with regression testing - **I found no regression**, which is good and we have same behavior overall, except 'known issues' ofc.
> 
> I found couple of bugs which I'm very certain existed before this push. I'll log those.

Awesome! Could you approve this PR and I'll merge it right away :)

**Review by Filipv95 — APPROVED** [review]

**Pull request merged**
