### PR TITLE
Offline screen

### PR DESCRIPTION
**Pull request by MiltonTulli**
# Description
Right now if Davi goes offline we get a white screen for multiple errors. Adding a wrapper around Router to display a "no internet connection" card. 

Closes https://github.com/DXgovernance/DAVI/issues/416

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

Screen Shot 2022-11-09 at 13 25 39

### CODE REVIEW

**Comment by Filipv95** [comment]
Looks good!

**Comment by dcrescimbeni** [comment]
The code looks good :+1:

I'm having a problem with the `<Discussions />` component: it makes it crash if you regain connection inside a Guild page. It doesn't crash if I remove the component.

Steps to reproduce:
1. Go to localhost
2. Select a guild
3. Disable wifi / connection. The offline page appears OK
4. Reenable connection
5. It shows a blank screen and an error in the console

Console screenshot:
image

Screen record:
https://www.loom.com/share/fd3d7510dbf546be95454fc9bbeb9692

**Comment by Filipv95** [comment]
Hey, @dcrescimbeni I was unable to reproduce the 'white screen' on my machine, tryed on 'Localhost', 'Goerli', 'Gnosis' networks with/without connected wallet, but I did had errors in the console.

For Localhost got this error in the console
localhost

**Review by mprasanjith — APPROVED** [review]

**Comment by MiltonTulli** [comment]
> The code looks good 👍
> 
> I'm having a problem with the `<Discussions />` component: it makes it crash if you regain connection inside a Guild page. It doesn't crash if I remove the component.
> 
> Steps to reproduce:
> 
> 1. Go to localhost
> 2. Select a guild
> 3. Disable wifi / connection. The offline page appears OK
> 4. Reenable connection
> 5. It shows a blank screen and an error in the console
> 
> Console screenshot: image
> 
> Screen record: https://www.loom.com/share/fd3d7510dbf546be95454fc9bbeb9692

@dcrescimbeni It was impossible to replicate for me. I think that is not related to this pr code and from what you said sounds like an existing Discussions component issue. If you think this is a blocker for current code added please provide more details on how can we replicate

**Comment by dcrescimbeni** [comment]
Agree. I'll try to replicate it and make a separate issue since it isn't related to this code.

**Pull request merged**
