### PR TITLE
Add summary for spending calls

### PR DESCRIPTION
**Pull request by MiltonTulli**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Closes https://github.com/DXgovernance/DAVI/issues/196

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

## Images
Screen Shot 2022-08-31 at 16 46 39

### CODE REVIEW

**Comment by Filipv95** [comment]
Hey @MiltonTulli I've noticed this error when tried to create add 'NFT Factory' action, other that than everything looks good.

https://user-images.githubusercontent.com/37701286/187981807-d6a71dc8-a2e0-450a-ab31-b897c1d32228.mp4

**Comment by MiltonTulli** [comment]
> Hey @MiltonTulli I've noticed this error when tried to create add 'NFT Factory' action, other than that, everything looks good.
> 
>  nftfactory.mp4

Good catch @Filipv95 ! Thanks for testing. 
Should be fixed now.

**Comment by Filipv95** [comment]
@MiltonTulli Looks good now, great job!

**Comment by dcrescimbeni** [comment]
LGTM :fire:

**Review by dcrescimbeni — APPROVED** [review]

**Pull request merged**
