### PR TITLE
Fixing white screen when url had no network

### LINKED ISSUE #447: White screen on url with no network
We still get white screens when the user goes straight to app.projectdavi.eth.limo/#/ and no network in the url

### PR DESCRIPTION
**Pull request by rulfo71**
# Added the case we dont have a last used chainId

Closes #447 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

open the app without specifying a chain

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rossneilson** [comment]
This works perfectly!!!

**Review by rossneilson — APPROVED** [review]

**Comment by Filipv95** [comment]
@rulfo71 hey not sure how to test this, when I go straight to `app.projectdavi.eth.limo/#/` `/gnosis` is being added automatically in the URL, can you pls explain how to test this?

**Comment by rossneilson** [comment]
I tested this by going to the preview deployment link of this PR
First behaviour before linking the wallet should be connecting to mainnet
Then after connecting wallet and then in a new tab navigating to /#/ of the preview URL, it should connect to mainnet with the wallet connected.
Then closing the tabs, changing wallet to gnosis chain and navigating again to /#/ of the preview URL we should see the UI connect to gnosis chain.
Also going directly to /#/gnosis of the preview URL should always take you to that network regardless of wallet status

**Comment by rulfo71** [comment]
@Filipv95 in your case /gnosis must be being added either because you used gnosis before or because you have your wallet connected to DAVI on gnosis chain

**Comment by Filipv95** [comment]
@rulfo71 @rossneilson Thank! That works as expected!

**Pull request merged**
