### PR TITLE
feat(TokenPicker): Implement native token support.

### LINKED ISSUE #141: Add native asset to asset lists
We currenlty list all erc20 tokens the guild has but we also need to allow native asset transfers. 
This will require manually adding to the list but also dealing with separately as it doesn't call a contract but instead directly sets `to` to the receiver and `value` is the amount with `data` blank.

### PR DESCRIPTION
**Pull request by mprasanjith**
# Description

Implements native token support for asset transfers in the action builder seamlessly alongside ERC20 transfers.

Closes #141.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally and using the existing test suite.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Review by rossneilson — DISMISSED** [review]

**Comment by Filipv95** [comment]
@rossneilson How can this be tested?

**Comment by rossneilson** [comment]
We have a new token that can be transferred, should show as ethereum on testnet and goerli

**Comment by Filipv95** [comment]
@rossneilson I've check this, new token is visible as 'ETH' in Transfer&Mint action, but I am unable to finish creating Proposal, is this perhaps expected behavior on localhost?

newtoken

**Comment by Filipv95** [comment]
@rossneilson I successfully created Proposal with 'Transfer&Mint' action and new ETH token! 
Screenshot 2022-08-22 at 18 06 11

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
