### PR TITLE
Update ipfs file to display correct "templateLiteral" for vesting contracts

### PR DESCRIPTION
**Pull request by MiltonTulli**
# Description
- Update rich contracts ipfs file with templateLiteral for vesting contract to be displayed properly on InfoLine component 

Closes https://github.com/DXgovernance/DAVI/issues/142

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

Screen Shot 2022-07-29 at 18 22 04

### CODE REVIEW

**Comment by rossneilson** [comment]
Its likely fine since its just a dev tool but not sure we need a new ipfs package for this since it is perfectly doable with the one we use normally

**Comment by rossneilson** [comment]
We also kind of need to pin the file in that script or else it will not stay around. Maybe for another issue though

**Comment by Kenny-Gin1** [comment]
Looks good! Maybe add a yarn command in the `package.json` as well? Is there a way we can know that we need to update our rich contracts on the IPFS at the moment? E.g. it took me some digging in the code before I realised that we didn't have template literals on the IPFS when I did this [issue](https://github.com/DXgovernance/DAVI/pulls)

**Comment by Kenny-Gin1** [comment]
The `templateLiteral` script disappeared from this PR. Did you upload it manually instead?

**Comment by Kenny-Gin1** [comment]
The `templateLiteral` script disappeared from this PR. Did you upload it manually instead?

**Comment by MiltonTulli** [comment]
> The `templateLiteral` script disappeared from this PR. Did you upload it manually instead?

Yes. We don't need that script.

**Review by Kenny-Gin1 — APPROVED** [review]
Looks good 🥇

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
