### PR TITLE
Fix useProposalCalls

### PR DESCRIPTION
**Pull request by MiltonTulli**
Fix useProposalCalls to display correct calls in ActionsBuilder options

### Issue
Proposal calls are being shown under the wrong option. 

### IMG of the issue
I added call details on the proposal description to be sure of how I submitted the proposal
Before3

### IMG after fix:
after3

### CODE REVIEW

**Review by Kenny-Gin1 — APPROVED** [review]
LGTM! ⭐

**Review by Kenny-Gin1 — APPROVED** [review]
@MiltonTulli Looks good! Could you however maybe add a screenshot of the issue you're fixing? The code in `useProposal` is quite complex so not sure of the intended behavior/UI sometimes :)

**Comment by MiltonTulli** [comment]
> 

@Kenny-Gin1 I added some images to describe and also a better description. This fix is what we saw in today's meeting regarding calls being assigned to the wrong option. We had 2 issues. [here](https://github.com/DXgovernance/DAVI/pull/285/files#diff-a9ea94b048bb6103839279a1fc926ce3deb0d5135723b8628dad88ee78c67b21L48) `callsPerOption` was wrong because was relying on `displayableOptionsNum` that was not considering empty or approval calls and at that point, we needed to consider all calls.  Also [HERE](https://github.com/DXgovernance/DAVI/pull/285/files#diff-a9ea94b048bb6103839279a1fc926ce3deb0d5135723b8628dad88ee78c67b21R69) we were returning null where we should return an empty call if the current call of the mapping was an approval call because that was affecting the total calls we returned (if expected 6, we were returning 5).

**Comment by Filipv95** [comment]
@MiltonTulli Looks good, great job!

**Pull request merged**
