### PR TITLE
Refactor theme config and update theme tokens.

### LINKED ISSUE #214: Sync themes with figma
Might need a sync up with Gero

### PR DESCRIPTION
**Pull request by mprasanjith**
# Description

Refactor color theme config of DAVI and updates usages across the app. The config has been simplified, with duplicate color tokens removed. Everything has been matched with the Figma.

Closes #214.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by Filipv95** [comment]
Hey @mprasanjith can you confirm that this is relevant figma link:

https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15606

**Review by dcrescimbeni — APPROVED** [review]

**Comment by dcrescimbeni** [comment]
Awesome job Madusha!

**Review by MiltonTulli — APPROVED** [review]
Looks good to me!
I was thinking about how we are using the theme and in my opinion we can consider adding a layer of `colors` or `palette` and all themes could consume that for creating it own keys like `text` or `muted`.
I created an example here https://github.com/MiltonTulli/DAVI/blob/feat/palette/src/theme/colors.ts

**Comment by mprasanjith** [comment]
> Hey @mprasanjith can you confirm that this is relevant figma link:
> 
> [figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15606](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15606)

Yes! The colors page is here: https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15324

**Comment by mprasanjith** [comment]
> Looks good to me! I was thinking about how we are using the theme and in my opinion we can consider adding a layer of `colors` or `palette` and all themes could consume that for creating it own keys like `text` or `muted`. I created an example here [https://github.com/MiltonTulli/DAVI/blob/feat/palette/src/theme/colors.ts](https://github.com/MiltonTulli/DAVI/blob/feat/palette/src/theme/colors.ts?rgh-link-date=2022-08-26T18%3A58%3A38Z)

Yeah, this is cool! Will make our life easier. Let's discuss more in the planning call.

**Comment by Filipv95** [comment]
@mprasanjith Looks good to me!

**Review by rossneilson — APPROVED** [review]

**Pull request merged**
