### PR TITLE
fix: Get storybook working with Wagmi.

### LINKED ISSUE #217: Fix storybook - WAGMI mock
It seems we have some WAGMI hooks breaking storybook that need mocking to make all the snapshots work properly

### PR DESCRIPTION
**Pull request by mprasanjith**
# Description

After trying multiple options to get a mock provider working, resorted to just adding a generic provider.

Closes #217.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by Filipv95** [comment]
Hey @mprasanjith,  is there a way to test this?

**Review by Kenny-Gin1 — APPROVED** [review]
LGTM!

**Comment by mprasanjith** [comment]
> Hey @mprasanjith, is there a way to test this?

I accidentally merged this, but can check by running `yarn storybook` locally, or checking the Storybook deployment link above. If this works all components in Storybook should render properly. (It wasn't, previously)

**Comment by Filipv95** [comment]
@mprasanjith tnx, I've ran `yarn storybook`, compile was successfull and I've checked Storybook, all components we rendered, looks good to me.

**Pull request merged**
