### PR TITLE
Feature/duration component

### PR DESCRIPTION
**Pull request by dcrescimbeni**
# Description

Added duration component. 

Closes #[806](https://github.com/DXgovernance/dxvote/issues/806)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manual and unit testing.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by rossneilson** [comment]
Since we are already formatting dates to appear as human readable and not unix could we do the same for duration?
Screenshot 2022-06-08 at 14 44 11

**Comment by dcrescimbeni** [comment]
Do you mean showing "1 year 2 months", or the end date from now like "08/08/2023"?

**Comment by dcrescimbeni** [comment]
Thoughts?

Screenshot from 2022-06-08 19-02-42

**Comment by rossneilson** [comment]
I agree, showing nothing matches the other components well, nice work

**Review by rossneilson — APPROVED** [review]

**Comment by dcrescimbeni** [comment]
This is a continuation of this PR present in the previous "dxvote" repo: https://github.com/DXgovernance/dxvote/pull/823

**Pull request merged**
